name: infinite_runner
description: An infinite runner game in Flutter

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  flame_audio: ^1.0.0
  box2d_flame: ^0.6.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
